// @flow
export const SET_CATEGORY = 'SET_CATEGORY';
export const ENTER_BATTLEMODE = 'ENTER_BATTLEMODE';
export const EXIT_BATTLEMODE = 'EXIT_BATTLEMODE';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const ANIMATE_LOSS = 'ANIMATE_LOSS';
export const SET_RECOMMENDATIONS = 'SET_RECOMMENDATIONS';
export const SET_RATING = 'SET_RATING';
export const ERROR_CLOSE = 'ERROR_CLOSE';
export const SET_TRENDS = 'SET_TRENDS';
export const SET_HOMEGIFLEFT = 'SET_HOMEGIFLEFT';
export const SET_HOMEGIFRIGHT = 'SET_HOMEGIFRIGHT';
